### ISSUE TITLE
Misplaced half marks in Caucasian Albanian

### ISSUE THREAD

**Issue by dscorbett** [notofonts/caucasian-albanian#1]
### Font
NotoSansCaucasianAlbanian-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/64f57055a31ee72789437d786e969ded9a1231f9/hinted/NotoSansCaucasianAlbanian-Regular.ttf
Date: 2018-11-28

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770

### Issue
The combining half marks don’t line up with the conjoining macrons. According to [L2/11-296R](https://www.unicode.org/L2/L2011/11296r-n4131r-caucasian-albanian.pdf#page=2) only the macrons are used in Caucasian Albanian, but the rest of glyphs should be fixed too as long as they’re in the font.

### Character data
𐔰︠𐔰︦𐔰︡
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE20 COMBINING LIGATURE LEFT HALF
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE26 COMBINING CONJOINING MACRON
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE21 COMBINING LIGATURE RIGHT HALF
𐔰︢𐔰︦𐔰︣
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE22 COMBINING DOUBLE TILDE LEFT HALF
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE26 COMBINING CONJOINING MACRON
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE23 COMBINING DOUBLE TILDE RIGHT HALF
𐔰︤𐔰︦𐔰︥
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE24 COMBINING MACRON LEFT HALF
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE26 COMBINING CONJOINING MACRON
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE25 COMBINING MACRON RIGHT HALF
𐔰︧𐔰︭𐔰︨
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE27 COMBINING LIGATURE LEFT HALF BELOW
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE2D COMBINING CONJOINING MACRON BELOW
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE28 COMBINING LIGATURE RIGHT HALF BELOW
𐔰︩𐔰︭𐔰︪
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE29 COMBINING TILDE LEFT HALF BELOW
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE2D COMBINING CONJOINING MACRON BELOW
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE2A COMBINING TILDE RIGHT HALF BELOW
𐔰︫𐔰︭𐔰︬
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE2B COMBINING MACRON LEFT HALF BELOW
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE2D COMBINING CONJOINING MACRON BELOW
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE2C COMBINING MACRON RIGHT HALF BELOW
𐔰︮𐔰︦𐔰︯
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE2E COMBINING CYRILLIC TITLO LEFT HALF
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE26 COMBINING CONJOINING MACRON
U+10530 CAUCASIAN ALBANIAN LETTER ALT
U+FE2F COMBINING CYRILLIC TITLO RIGHT HALF

### Screenshot
![𐔰︠𐔰︦𐔰︡ 𐔰︢𐔰︦𐔰︣ 𐔰︤𐔰︦𐔰︥ 𐔰︧𐔰︭𐔰︨ 𐔰︩𐔰︭𐔰︪ 𐔰︫𐔰︭𐔰︬ 𐔰︮𐔰︦𐔰︯](https://user-images.githubusercontent.com/1124347/49173552-10b41b80-f312-11e8-8413-03efb338f10f.png)

**Comment by marekjez86** [comment]
@dscorbett : we have received a new sources. I built the fonts and tested them.
The current results are as follows:
![aghb-1394](https://user-images.githubusercontent.com/13322623/53539910-419a1d00-3ac8-11e9-92a4-45c8eb5fd2ff.jpeg)



TTF https://github.com/googlei18n/noto-fonts/blob/master/phaseIII_only/unhinted/ttf/NotoSansCaucasianAlbanian/NotoSansCaucasianAlbanian-Regular.ttf?raw=true or OTF https://github.com/googlei18n/noto-fonts/blob/master/phaseIII_only/unhinted/otf/NotoSansCaucasianAlbanian/NotoSansCaucasianAlbanian-Regular.otf?raw=true


Response from the font developer is below
"====================================="
Cases requiring corrections:    1, 4, 7
"--"
Inappropriate use, but needs no correction:    2, 5
See illustration below.
"--"
Ok as is:    3, 6
 

Here are before and after In the order shown in the report.
 
1. Combining Ligatures Above (FE20, FE26, FE21) ✅
![image001](https://user-images.githubusercontent.com/13322623/53540213-70fd5980-3ac9-11e9-9461-6058d751a7c1.png)

2. Combining Double Tildes Above (FE22, FE26, FE23) ❌
 ![image02](https://user-images.githubusercontent.com/13322623/53540189-5dea8980-3ac9-11e9-8dde-0d6e652c5fcb.png)
These two marks are not meant to combine with FE26 and stretch across more than 2 letters.
The proper way to use them is over two letters like this:
![image2b](https://user-images.githubusercontent.com/13322623/53540177-57f4a880-3ac9-11e9-8a42-1a5f83bab4b5.jpg)

3. Combining Macrons Above (FE24, FE26, FE25) ✅
![image03](https://user-images.githubusercontent.com/13322623/53540169-4dd2aa00-3ac9-11e9-8553-7194281cca17.png)

4. Combining Ligatures Below (FE27, FE26, FE28) ✅
![image04](https://user-images.githubusercontent.com/13322623/53540165-47443280-3ac9-11e9-9562-25bfe59010a0.png)
 
5. Combining Tildes Below (FE29, FE26, FE2A) ❌
![image05](https://user-images.githubusercontent.com/13322623/53540153-3c899d80-3ac9-11e9-8f58-1a71b6a0d9be.png)
These two marks are not meant to combine with FE26 and stretch across more than 2 letters.
The proper way to use them is under two letters like this:
![image05b](https://user-images.githubusercontent.com/13322623/53540147-32679f00-3ac9-11e9-99d3-1acb9f2b9078.jpg)

6. Combining Macrons Below (FE2B, FE26, FE2C) ✅
![image06](https://user-images.githubusercontent.com/13322623/53540137-28de3700-3ac9-11e9-8278-ee45079e81b2.png)

7. Combining Cyrillic Titlos (FE2E, FE26, FE2F) ✅
![image07](https://user-images.githubusercontent.com/13322623/53540121-1bc14800-3ac9-11e9-9637-a1a0396d571f.png)

**Comment by dscorbett** [comment]
This is better, but the tildes really are meant to be used with the conjoining macrons. See [L2/11-224](https://www.unicode.org/L2/L2011/11224-n4078.pdf), where the tilde halves below were first proposed as COMBINING TILDE BELOW LEFT HALF and COMBINING LIGATURE OR TILDE BELOW RIGHT HALF explicitly to implement a triple tilde, and [the Combining Half Marks code chart](https://www.unicode.org/charts/PDF/UFE20.pdf), which says “These are used in combinations to represent a ligature, tilde, or macron that extend underneath more than two characters”.

Alternatively, this font could simply not support the tildes, because they are not used in Caucasian Albanian.

**Comment by simoncozens** [comment]
I think if the shape of the tildes is not suitable for conjoining macrons, and tildes are not used in Caucasian Albanian, I'm going to set them to non-exported. However, there is another nit here; the Unicode standard says

> An abbreviation sign is used spanning two letters in a way similar to that of U+2CEF COPTIC COMBINING NI ABOVE does; an example is  K͡S krisṭos. It is recommended to use the generic diacritic U+035E COMBINING DOUBLE MACRON for this.

So this font should probably include 035E...

**Comment by simoncozens** [comment]
OK, this is even more tricky than I thought. My reading of the proposal (L2/11-296R) is that:

* Macron and combining (/conjoining) macron characters should be used to overline abbreviations.
* In the manuscripts, these overlines are titlo-shaped.
* Nevertheless we should use the MACRON characters, but "let the font deal with the swash ends of the diacritic"...
* "...in font styles that require it."
* The above also goes for numerals.

I'm going to take from this:

* The font should only contain the following combining marks:
  * U+0304 COMBINING MACRON
  * U+0331 COMBINING MACRON BELOW
  * U+FE24 COMBINING MACRON LEFT HALF
  * U+FE25 COMBINING MACRON RIGHT HALF
  * U+FE26 COMBINING CONJOINING MACRON
  * U+FE2B COMBINING MACRON LEFT HALF BELOW
  * U+FE2C COMBINING MACRON RIGHT HALF BELOW
  * U+FE2D COMBINING CONJOINING MACRON BELOW
  * (and U+035E, of course)
* Noto Sans Caucasian Albian is a sans style, so I'm going to claim we are not a "font style that requires" swash ends, and so the macron characters will be straight macrons.
