### ISSUE TITLE
Conjoining macrons do not conjoin

### ISSUE THREAD

**Issue by dscorbett** [notofonts/caucasian-albanian#3]
### Font
NotoSansCaucasianAlbanian-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/caucasian-albanian/releases/tag/NotoSansCaucasianAlbanian-v2.004
Date: 2022-09-21

### Font version
Version 2.004

### Issue
The lookups that set the widths of U+FE26 and U+FE2D according to their bases never actually get applied. This means that when the base is wider than the default macron glyph, the macron fails to conjoin to an adjacent cluster’s macron.

Instead of precomposed glyphs of base and macron, which the font is currently trying to do, I recommend using separate macron glyphs, contextualized to different lengths. This seems like a simpler design to me. However, however you want to implement it is fine as long as the final appearance is correct.

### Character data
𐕙︦𐕙︦
U+10559 CAUCASIAN ALBANIAN LETTER RAT
U+FE26 COMBINING CONJOINING MACRON
U+10559 CAUCASIAN ALBANIAN LETTER RAT
U+FE26 COMBINING CONJOINING MACRON

### Screenshot
![𐕙︦𐕙︦](https://user-images.githubusercontent.com/1124347/191516213-50083475-2be7-4153-b2f5-8a1b4c484239.png)

**Comment by simoncozens** [comment]
It is a simpler design, but I just made the lookups work again and it seems to be OK.
