### ISSUE TITLE
Mark attachment fails in DFLT script

### ISSUE THREAD

**Issue by dscorbett** [notofonts/caucasian-albanian#4]
### Font
NotoSansCaucasianAlbanian-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/caucasian-albanian/releases/tag/NotoSansCaucasianAlbanian-v2.004
Date: 2022-09-21

### Font version
Version 2.004

### Issue
Marks are not attached to U+25CC DOTTED CIRCLE when the script tag is DFLT, as opposed to 'aghb'.

### Character data
◌̄
U+25CC DOTTED CIRCLE
U+0304 COMBINING MACRON

### Screenshot
![◌̄](https://user-images.githubusercontent.com/1124347/191519731-78b00d60-ccd3-438a-a279-935295398519.png)

**Comment by simoncozens** [comment]
This seems to have been fixed with a rebuild.
